spring:
  application.name: withaeng-api
  profiles.default: local
  config.import:
    - application-domain.yml
    - application-external.yml
  web.resources.add-mappings: false

witheang:
  auth:
    jwt-issuer: ${JWT_ISSUER}
    jwt-secret-key: ${JWT_SECRET_KEY}

jasypt.encryptor.password: ${JASYPT_PASSWORD}

---
spring.config.activate.on-profile: local

springdoc:
  swagger-ui:
    path: /api-docs
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

---
spring.config.activate.on-profile: dev

springdoc:
  swagger-ui:
    path: /api-docs
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

---
spring.config.activate.on-profile: prod

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
